# =============================================================================
# -----------------------------------------------------------------------------
#               HOSPITAL LENGTH OF STAY (LOS) END-TO-END PIPELINE
# -----------------------------------------------------------------------------
# =============================================================================

# =============================================================================
# PART 1: INITIALIZATION AND EXPLORATORY DATA ANALYSIS (EDA)
# =============================================================================

# -*- coding: utf-8 -*-
"""LengthOfSta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuBqK6mIKl6BWLCpI4CYJvjDTQzZ2tgM

##Dataset Analys
"""

# ==============================
# LOS DATASET EXPLORATORY ANALYSIS
# ==============================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------------
# 1. LOAD DATASET
# ------------------------------
df = pd.read_csv("LengthOfStay.csv")   # <-- change path

print("\n===== FIRST 5 ROWS =====")
print(df.head())

# ------------------------------
# 2. SHAPE & INFO
# ------------------------------
print("\n===== DATASET SHAPE =====")
print(df.shape)

print("\n===== DATASET INFO =====")
print(df.info())

# ------------------------------
# 3. MISSING VALUES
# ------------------------------
print("\n===== MISSING VALUES =====")
print(df.isnull().sum())

print("\n===== MISSING % =====")
print((df.isnull().sum() / len(df)) * 100)

# ------------------------------
# 4. LOS DISTRIBUTION
# ------------------------------
plt.figure(figsize=(8,5))
plt.hist(df['lengthofstay'], bins=30)
plt.title("Length of Stay Distribution")
plt.xlabel("Days")
plt.ylabel("Count")
plt.show()

# ------------------------------
# 5. LOS STATS
# ------------------------------
print("\n===== LOS STATS =====")
print(df['lengthofstay'].describe())

# ------------------------------
# 6. CATEGORICAL VALUE CHECK
# ------------------------------
print("\n===== GENDER VALUES =====")
print(df['gender'].value_counts())

print("\n===== RCOUNT VALUES =====")
print(df['rcount'].value_counts())

print("\n===== FACILITY VALUES =====")
print(df['facid'].value_counts())

# ------------------------------
# 7. CORRELATION HEATMAP
# ------------------------------
plt.figure(figsize=(12,8))
sns.heatmap(df.corr(numeric_only=True), cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# ------------------------------
# 8. LOS vs COMORBIDITIES
# ------------------------------
cols = [
    'dialysisrenalendstage',
    'asthma',
    'malnutrition',
    'fibrosisandother'
]

for col in cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=col, y='lengthofstay', data=df)
    plt.title(f"{col} vs LOS")
    plt.show()

# ------------------------------
# 9. OUTLIER CHECK
# ------------------------------
plt.figure(figsize=(6,4))
sns.boxplot(x=df['lengthofstay'])
plt.title("LOS Outliers")
plt.show()

print("\n===== EDA COMPLETED =====")


# =============================================================================
# PART 2: DATA PREPROCESSING AND FEATURE ENGINEERING
# =============================================================================

import pandas as pd

df = pd.read_csv("LengthOfStay.csv")

# -------- rcount fix --------
df['rcount'] = df['rcount'].replace('5+', 5).astype(int)

# -------- encode gender --------
df['gender'] = df['gender'].map({'F':0, 'M':1})

# -------- encode facility --------
df = pd.get_dummies(df, columns=['facid'], drop_first=True)

# -------- create LOS category --------
def los_category(x):
    if x <= 3:
        return 0
    elif x <= 6:
        return 1
    else:
        return 2

df['los_cat'] = df['lengthofstay'].apply(los_category)

# -------- drop unused columns --------
df = df.drop(['eid','vdate','discharged','lengthofstay'], axis=1)

print(df.head())
print(df['los_cat'].value_counts())

df.to_csv("processed_los.csv", index=False)


# =============================================================================
# PART 3: UNSUPERVISED LEARNING (PCA & K-MEANS CLUSTERING)
# =============================================================================

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------
# LOAD DATA
# -----------------------
df = pd.read_csv("processed_los.csv")

X = df.drop("los_cat", axis=1)

# -----------------------
# SCALE DATA
# -----------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -----------------------
# PCA REDUCTION
# -----------------------
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

print("Explained variance:", pca.explained_variance_ratio_)

# -----------------------
# KMEANS CLUSTERING
# -----------------------
kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

# -----------------------
# PLOT CLUSTERS
# -----------------------
plt.figure(figsize=(8,6))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=clusters, palette="viridis", s=15)
plt.title("Patient Clustering (PCA + KMeans)")
plt.show()

# -----------------------
# COMPARE WITH TRUE LOS
# -----------------------
plt.figure(figsize=(8,6))
sns.scatterplot(x=X_pca[:,0], y=X_pca[:,1], hue=df['los_cat'], palette="Set1", s=15)
plt.title("Actual LOS Categories")
plt.show()


# =============================================================================
# PART 4: BASELINE PREDICTIVE MODELING (RANDOM FOREST)
# =============================================================================

# --- 4.1 Train & Evaluate Random Forest ---

# ==============================
# LOS BASELINE MODEL (RANDOM FOREST)
# ==============================

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib

# ------------------------------
# 1. LOAD PROCESSED DATA
# ------------------------------
df = pd.read_csv("processed_los.csv")

print("\n===== DATA SHAPE =====")
print(df.shape)

# ------------------------------
# 2. SPLIT FEATURES & TARGET
# ------------------------------
X = df.drop("los_cat", axis=1)
y = df["los_cat"]

# ------------------------------
# 3. TRAIN TEST SPLIT
# ------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("\nTrain size:", X_train.shape)
print("Test size:", X_test.shape)

# ------------------------------
# 4. TRAIN MODEL
# ------------------------------
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

# ------------------------------
# 5. PREDICTION
# ------------------------------
pred = model.predict(X_test)

# ------------------------------
# 6. EVALUATION
# ------------------------------
print("\n===== ACCURACY =====")
print(accuracy_score(y_test, pred))

print("\n===== CLASSIFICATION REPORT =====")
print(classification_report(y_test, pred))

print("\n===== CONFUSION MATRIX =====")
print(confusion_matrix(y_test, pred))

# ------------------------------
# 7. SAVE MODEL
# ------------------------------
joblib.dump(model, "los_rf_model.pkl")
print("\nModel saved as los_rf_model.pkl")

# --- 4.2 Inference / Predict Single Sample with Random Forest ---

import joblib
import pandas as pd

# -------------------------
# 1. LOAD MODEL
# -------------------------
model = joblib.load("los_rf_model.pkl")

print("Model loaded successfully")

# -------------------------
# 2. CREATE SAMPLE PATIENT
# (values must match training columns)
# -------------------------

sample = {
    'rcount': 1,
    'gender': 1,
    'dialysisrenalendstage': 0,
    'asthma': 0,
    'irondef': 0,
    'pneum': 0,
    'substancedependence': 0,
    'psychologicaldisordermajor': 0,
    'depress': 0,
    'psychother': 0,
    'fibrosisandother': 0,
    'malnutrition': 0,
    'hemo': 13,
    'hematocrit': 40,
    'neutrophils': 8,
    'sodium': 138,
    'glucose': 120,
    'bloodureanitro': 12,
    'creatinine': 1.0,
    'bmi': 28,
    'pulse': 80,
    'respiration': 6,
    'secondarydiagnosisnonicd9': 1,
    'facid_B': 1,
    'facid_C': 0,
    'facid_D': 0,
    'facid_E': 0
}

sample_df = pd.DataFrame([sample])

# -------------------------
# 3. PREDICT
# -------------------------
pred = model.predict(sample_df)

# -------------------------
# 4. INTERPRET OUTPUT
# -------------------------
mapping = {
    0: "Short Stay (1–3 days)",
    1: "Medium Stay (4–6 days)",
    2: "Long Stay (7+ days)"
}

print("\nPrediction:", mapping[pred[0]])


# =============================================================================
# PART 5: ADVANCED PREDICTIVE MODELING (CATBOOST)
# =============================================================================

# --- 5.1 Train & Evaluate CatBoost ---

!pip install catboost

# ==============================
# LOS MODEL - CATBOOST
# ==============================

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from catboost import CatBoostClassifier
import joblib

# ------------------------------
# 1. LOAD DATA
# ------------------------------
df = pd.read_csv("processed_los.csv")

X = df.drop("los_cat", axis=1)
y = df["los_cat"]

# ------------------------------
# 2. TRAIN TEST SPLIT
# ------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ------------------------------
# 3. TRAIN CATBOOST
# ------------------------------
model = CatBoostClassifier(
    iterations=300,
    depth=6,
    learning_rate=0.1,
    loss_function='MultiClass',
    verbose=100
)

model.fit(X_train, y_train)

# ------------------------------
# 4. PREDICTION
# ------------------------------
pred = model.predict(X_test)

# ------------------------------
# 5. EVALUATION
# ------------------------------
print("\n===== ACCURACY =====")
print(accuracy_score(y_test, pred))

print("\n===== CLASSIFICATION REPORT =====")
print(classification_report(y_test, pred))

print("\n===== CONFUSION MATRIX =====")
print(confusion_matrix(y_test, pred))

# ------------------------------
# 6. SAVE MODEL
# ------------------------------
joblib.dump(model, "los_catboost_model.pkl")
print("\nModel saved as los_catboost_model.pkl")

# --- 5.2 Compare Random Forest vs CatBoost Predictions ---

import joblib
import pandas as pd

# -------------------------
# LOAD BOTH MODELS
# -------------------------
rf_model = joblib.load("los_rf_model.pkl")
cat_model = joblib.load("los_catboost_model.pkl")

print("Both models loaded successfully")

# -------------------------
# SAMPLE PATIENT (same as before)
# -------------------------
sample = {
    'rcount': 1,
    'gender': 1,
    'dialysisrenalendstage': 0,
    'asthma': 0,
    'irondef': 0,
    'pneum': 0,
    'substancedependence': 0,
    'psychologicaldisordermajor': 0,
    'depress': 0,
    'psychother': 0,
    'fibrosisandother': 0,
    'malnutrition': 0,
    'hemo': 13,
    'hematocrit': 40,
    'neutrophils': 8,
    'sodium': 138,
    'glucose': 120,
    'bloodureanitro': 12,
    'creatinine': 1.0,
    'bmi': 28,
    'pulse': 80,
    'respiration': 6,
    'secondarydiagnosisnonicd9': 1,
    'facid_B': 1,
    'facid_C': 0,
    'facid_D': 0,
    'facid_E': 0
}

sample_df = pd.DataFrame([sample])

# -------------------------
# PREDICTIONS
# -------------------------
rf_pred = rf_model.predict(sample_df)[0]
cat_pred = cat_model.predict(sample_df)[0]

mapping = {
    0: "Short Stay (1–3 days)",
    1: "Medium Stay (4–6 days)",
    2: "Long Stay (7+ days)"
}

print("\n===== PREDICTIONS =====")
print("Random Forest:", mapping[rf_pred])
print("CatBoost:", mapping[int(cat_pred)])

# -------------------------
# PROBABILITIES
# -------------------------
rf_prob = rf_model.predict_proba(sample_df)[0]
cat_prob = cat_model.predict_proba(sample_df)[0]

print("\n===== RANDOM FOREST CONFIDENCE =====")
print(f"Short: {rf_prob[0]*100:.2f}%")
print(f"Medium: {rf_prob[1]*100:.2f}%")
print(f"Long: {rf_prob[2]*100:.2f}%")

print("\n===== CATBOOST CONFIDENCE =====")
print(f"Short: {cat_prob[0]*100:.2f}%")
print(f"Medium: {cat_prob[1]*100:.2f}%")
print(f"Long: {cat_prob[2]*100:.2f}%")


# =============================================================================
# PART 6: MODEL EXPLAINABILITY & FEATURE IMPORTANCE
# =============================================================================

# --- 6.1 Built-in Feature Importance ---

import joblib
import pandas as pd
import matplotlib.pyplot as plt

# -----------------------
# LOAD MODEL + DATA
# -----------------------
model = joblib.load("los_catboost_model.pkl")
df = pd.read_csv("processed_los.csv")

X = df.drop("los_cat", axis=1)

# -----------------------
# GET FEATURE IMPORTANCE
# -----------------------
importance = model.get_feature_importance()
features = X.columns

imp_df = pd.DataFrame({
    "feature": features,
    "importance": importance
}).sort_values(by="importance", ascending=False)

print("\n===== TOP FEATURES =====")
print(imp_df.head(15))

# -----------------------
# PLOT
# -----------------------
plt.figure(figsize=(8,6))
plt.barh(imp_df["feature"][:15][::-1], imp_df["importance"][:15][::-1])
plt.title("Top 15 Features Influencing LOS")
plt.xlabel("Importance")
plt.show()

# --- 6.2 SHAP Values Analysis ---

!pip install shap

import shap
import joblib
import pandas as pd
import matplotlib.pyplot as plt

# ----------------------
# LOAD MODEL + DATA
# ----------------------
model = joblib.load("los_catboost_model.pkl")
df = pd.read_csv("processed_los.csv")

X = df.drop("los_cat", axis=1)

# ----------------------
# SAMPLE DATA
# ----------------------
sample = X.sample(2000, random_state=42)

# ----------------------
# EXPLAINER
# ----------------------
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(sample)

# ----------------------
# BAR PLOT (VERY CLEAN)
# ----------------------
plt.figure(figsize=(10,6))
shap.summary_plot(
    shap_values,
    sample,
    plot_type="bar",
    max_display=12,
    show=False
)

plt.title("Most Important Factors Affecting Hospital Stay", fontsize=14)
plt.tight_layout()
plt.show()

import shap
import joblib
import pandas as pd

# ----------------------
# LOAD MODEL
# ----------------------
model = joblib.load("los_catboost_model.pkl")

# ----------------------
# CREATE SAMPLE PATIENT
# ----------------------
sample = {
    'rcount': 3,
    'gender': 1,
    'dialysisrenalendstage': 0,
    'asthma': 0,
    'irondef': 0,
    'pneum': 0,
    'substancedependence': 0,
    'psychologicaldisordermajor': 1,
    'depress': 0,
    'psychother': 0,
    'fibrosisandother': 0,
    'malnutrition': 0,
    'hemo': 11,
    'hematocrit': 35,
    'neutrophils': 10,
    'sodium': 135,
    'glucose': 180,
    'bloodureanitro': 14,
    'creatinine': 1.6,
    'bmi': 31,
    'pulse': 95,
    'respiration': 7,
    'secondarydiagnosisnonicd9': 2,
    'facid_B': 0,
    'facid_C': 0,
    'facid_D': 0,
    'facid_E': 1
}

sample_df = pd.DataFrame([sample])

# ----------------------
# PREDICT
# ----------------------
pred = int(model.predict(sample_df)[0])

mapping = {
    0: "Short Stay (1–3 days)",
    1: "Medium Stay (4–6 days)",
    2: "Long Stay (7+ days)"
}

print("\nPrediction:", mapping[pred])

# ----------------------
# SHAP EXPLANATION
# ----------------------
explainer = shap.TreeExplainer(model)
shap_values = explainer(sample_df)

# explain predicted class
shap.plots.waterfall(shap_values[0][:, pred])